disabled = false
languageCode = "zh-cnn"
languageName = "Chinese"
weight = 1
title = "Blog | 树响集"
contentDir = 'content/zh-cn'

[params]
  displayName = "简体中文"
  isoCode = "zh-CN"
  rtl = false
  dateFormat = "2006年1月2日"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "My awesome website"
  copyright = "<small>© 作者保留所有权利，禁止转载。<br>由 Hugo 和 Blowfish 驱动。"

[params.author]
name = "树响集"
image = "img/502178ldsdl.jpg"
#   imageQuality = 96
headline = "不作诗则做诗"
#   bio = "A little bit about you"
links = [
    { github = "https://github.com/wbzddwsw/one" },
    { star = "https://stelpolva.moe/@donbro" },
    { film-solid = "https://tube.pari.cafe/a/wsw/video-channels" },
    { weibo-brands = "https://weibo.com/u/2506091025" },
]
