[[main]]
none = "none"

[[main]]
name = "首页"
pageRef = "/"
identifier = "134FlykbLj"
weight = 1


[[main]]
name = "文章"
pageRef = "posts"
identifier = "qSeOC4dLVM"
weight = 2

[[main]]
name = "归档"
url = "#"
identifier = "fRH25WinUX"
weight = 3

    [[main]]
    name = "分类"
    pageRef = "categories"
    parent = "fRH25WinUX"
    weight = 1

    [[main]]
    name = "标签"
    pageRef = "tags"
    parent = "fRH25WinUX"
    weight = 2

[[main]]
name = "更多"
url = "#"
identifier = "more46more"
weight = 4

    [[main]]
    name = "友链"
    pageRef = "friends"
    parent = "more46more"
    weight = 2

    [[main]]
    name = "关于"
    pageRef = "about"
    parent = "more46more"
    weight = 1

[[footer]]
none = "none"
